/*
 * Copyright (C) 2019 Rodolfo Navarro B.
 *
 * This program is free software: you can redistribute it and/or modify
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
 */
package co.cr.ACAT;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author Rodolfo Navarro
 */
public class JDSyl extends javax.swing.JDialog {

    /**
     * Creates new form JDSyl
     */
    private final Timer mtcycle;
    private int indT=0;
    private int set_op=0;
    private String jpFocus;
    public String kdef;
    private long startTime = System.currentTimeMillis();
    private int totalTime = 20000;
    private boolean toFinish = false;
    
    public JDSyl(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mtcycle = new Timer();
        mtcycle.scheduleAtFixedRate(timerTask, 0, 500);

    }

    TimerTask timerTask = new TimerTask() 
     { 
         public void run()  
         {
            toFinish = (System.currentTimeMillis() - startTime >= totalTime);
            if (!toFinish){
              Border mbf;
                if (indT==0) {
                    mbf=BorderFactory.createMatteBorder(3, 3, 3, 3, Color.yellow);
                } else {
                    mbf=BorderFactory.createEmptyBorder();
                }

                jpCycleUsedW();  
            } else {
                set_op=4;
                ExecSO("");
            }
         } 
    };
    
    public void ReceiveLetter(String lett_show){
        this.jTextField2.setText(lett_show);
        String ltadd="";
        switch (lett_show){
            case "a":
                ltadd="á";
                break;
            case "e":
                ltadd="é";
                break;
            case "i":
                ltadd="í";
                break;
            case "o":
                ltadd="ó";
                break;
            case "u":
                ltadd="ú";
                break;
            case "n":
                ltadd="ñ";
                break;
        }
        this.jTextField3.setText(ltadd);
    }
    
    private void jpCycleUsedW() {
        for (int i=1;i<5;i++) {
            if (i>1){
                jpFocus="jpSyl"+ i;
                JPanel jp =Awt1.getComponentByName(this, jpFocus);
                jp.setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.yellow));

                int tms=1500;
                try {
                    sleep(tms);
                } catch (InterruptedException ex) {
                    Logger.getLogger(KeyboardK.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(indT==1){
                    for(Component component : jp.getComponents()) {
                        JTextField key = (JTextField)component;
                        //SpeakTxt(key.getText());
                        set_op=i;
                        indT=0;
                        ExecSO(key.getText());
                    }
                }
                jp.setBorder(BorderFactory.createEmptyBorder());
            }
        }
        set_op=0;
    }
    
    private void ExecSO(String letsel){
        //mtcycle.cancel();
        kdef=letsel;
        switch (set_op) {
            case 4:
                kdef="";
                this.dispose();
                break;
            case 3:
                this.dispose();
                break;
            case 2:
                this.dispose();
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpSyl1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jpSyl2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jpSyl3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jpSyl4 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyPressedF12(evt);
            }
        });

        javax.swing.GroupLayout jpSyl1Layout = new javax.swing.GroupLayout(jpSyl1);
        jpSyl1.setLayout(jpSyl1Layout);
        jpSyl1Layout.setHorizontalGroup(
            jpSyl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        jpSyl1Layout.setVerticalGroup(
            jpSyl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel1.add(jpSyl1);

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("a");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressedF12(evt);
            }
        });

        javax.swing.GroupLayout jpSyl2Layout = new javax.swing.GroupLayout(jpSyl2);
        jpSyl2.setLayout(jpSyl2Layout);
        jpSyl2Layout.setHorizontalGroup(
            jpSyl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        jpSyl2Layout.setVerticalGroup(
            jpSyl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel1.add(jpSyl2);

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("á");
        jTextField3.setToolTipText("");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressedF12(evt);
            }
        });

        javax.swing.GroupLayout jpSyl3Layout = new javax.swing.GroupLayout(jpSyl3);
        jpSyl3.setLayout(jpSyl3Layout);
        jpSyl3Layout.setHorizontalGroup(
            jpSyl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        jpSyl3Layout.setVerticalGroup(
            jpSyl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel1.add(jpSyl3);

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("X");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressedF12(evt);
            }
        });

        javax.swing.GroupLayout jpSyl4Layout = new javax.swing.GroupLayout(jpSyl4);
        jpSyl4.setLayout(jpSyl4Layout);
        jpSyl4Layout.setHorizontalGroup(
            jpSyl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        jpSyl4Layout.setVerticalGroup(
            jpSyl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel1.add(jpSyl4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        set_op=2;
        ExecSO(jTextField2.getText());
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2KeyPressedF12(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressedF12
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F12) {
            indT=1;
        }
    }//GEN-LAST:event_jTextField2KeyPressedF12

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        set_op=3;
        ExecSO(jTextField3.getText());
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField3KeyPressedF12(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressedF12
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F12) {
            indT=1;
        }
    }//GEN-LAST:event_jTextField3KeyPressedF12

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
        set_op=4;
        ExecSO(jTextField4.getText());
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField4KeyPressedF12(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressedF12
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F12) {
            indT=1;
        }
    }//GEN-LAST:event_jTextField4KeyPressedF12

    private void KeyPressedF12(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyPressedF12
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F12) {
            indT=1;
        }
    }//GEN-LAST:event_KeyPressedF12

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDSyl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDSyl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDSyl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDSyl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDSyl dialog = new JDSyl(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel jpSyl1;
    private javax.swing.JPanel jpSyl2;
    private javax.swing.JPanel jpSyl3;
    private javax.swing.JPanel jpSyl4;
    // End of variables declaration//GEN-END:variables
}
 

